version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_DB=weather_app
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-db
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn Back_Weather_App.wsgi:application --bind 0.0.0.0:5050"
    volumes:
      - ./backend:/app
    ports:
      - "5050:5050"
    environment:
      - DEBUG=0
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEATHER_KEY_ONE_CALL=${WEATHER_KEY_ONE_CALL}
    depends_on:
      - db
      - redis
    networks:
      - backend-db
      - frontend-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_HOST=backend
    depends_on:
      - backend
    networks:
      - frontend-backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - frontend-backend

  zabbix-db:
    image: postgres:17
    container_name: zabbix-db
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - zabbix-net
    volumes:
      - zabbix_db_data:/var/lib/postgresql/data/

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=zabbix
    depends_on:
      - zabbix-db
    networks:
      - zabbix-net
    ports:
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    ports:
      - "8888:8080"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    user: root
    privileged: true
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=docker-host
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      - zabbix-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend-db:
    driver: bridge
  frontend-backend:
    driver: bridge
  zabbix-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
  zabbix_server_data:
  zabbix_db_data: